/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/Views/**/*.php',
    './public/index.php',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary:    'var(--color-primary)',
        secondary:  'var(--color-secondary)',
        background: 'var(--color-background)',
        surface:    'var(--color-surface)',
        text:       'var(--color-text)',
        muted:      'var(--color-muted)',
        border:     'var(--color-border)',

        'on-secondary':               'var(--color-on-secondary)',
        'primary-container':          'var(--color-primary-container)',
        'surface-container-low':      'var(--color-surface-container-low)',
        'inverse-on-surface':         'var(--color-inverse-on-surface)',
        'on-primary-fixed-variant':   'var(--color-on-primary-fixed-variant)',
        'primary-fixed-dim':          'var(--color-primary-fixed-dim)',
        'on-tertiary-fixed-variant':  'var(--color-on-tertiary-fixed-variant)',
        'inverse-primary':            'var(--color-inverse-primary)',
        'surface-variant':            'var(--color-surface-variant)',
        'on-tertiary':                'var(--color-on-tertiary)',
        'primary-fixed':              'var(--color-primary-fixed)',
        'outline-variant':            'var(--color-outline-variant)',
        'surface-container-high':     'var(--color-surface-container-high)',
        'tertiary-container':         'var(--color-tertiary-container)',
        'on-surface':                 'var(--color-on-surface)',
        'error':                      'var(--color-error)',
        'surface-dim':                'var(--color-surface-dim)',
        'on-error-container':         'var(--color-on-error-container)',
        'outline':                    'var(--color-outline)',
        'tertiary-fixed-dim':         'var(--color-tertiary-fixed-dim)',
        'tertiary':                   'var(--color-tertiary)',
        'on-error':                   'var(--color-on-error)',
        'surface-container-lowest':   'var(--color-surface-container-lowest)',
        'surface-container-highest':  'var(--color-surface-container-highest)',
        'surface-container':          'var(--color-surface-container)',
        'error-container':            'var(--color-error-container)',
        'on-tertiary-fixed':          'var(--color-on-tertiary-fixed)',
        'on-secondary-container':     'var(--color-on-secondary-container)',
        'surface-bright':             'var(--color-surface-bright)',
        'on-secondary-fixed':         'var(--color-on-secondary-fixed)',
        'secondary-fixed-dim':        'var(--color-secondary-fixed-dim)',
        'surface-tint':               'var(--color-surface-tint)',
        'on-tertiary-container':      'var(--color-on-tertiary-container)',
        'on-primary':                 'var(--color-on-primary)',
        'tertiary-fixed':             'var(--color-tertiary-fixed)',
        'secondary-fixed':            'var(--color-secondary-fixed)',
        'on-primary-container':       'var(--color-on-primary-container)',
        'secondary-container':        'var(--color-secondary-container)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'on-background':              'var(--color-on-background)',
        'on-primary-fixed':           'var(--color-on-primary-fixed)',
        'on-surface-variant':         'var(--color-on-surface-variant)',
        'inverse-surface':            'var(--color-inverse-surface)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        full:    '9999px',
      },
      spacing: {
        'margin-desktop': '48px',
        'margin-mobile':  '16px',
        'container-max':  '1280px',
        'unit':           '8px',
        'gutter':         '24px',
      },
      fontFamily: {
        sans:                ['Outfit', 'Inter', 'sans-serif'],
        'headline-lg':       ['Montserrat'],
        'label-md':          ['Inter'],
        'display-lg':        ['Montserrat'],
        'headline-md':       ['Montserrat'],
        'label-sm':          ['Inter'],
        'body-lg':           ['Inter'],
        'body-md':           ['Inter'],
        'headline-lg-mobile':['Montserrat'],
      },
      fontSize: {
        'headline-lg':        ['32px', { lineHeight: '40px',  fontWeight: '700' }],
        'label-md':           ['14px', { lineHeight: '20px',  letterSpacing: '0.01em', fontWeight: '600' }],
        'display-lg':         ['48px', { lineHeight: '56px',  letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md':        ['24px', { lineHeight: '32px',  fontWeight: '600' }],
        'label-sm':           ['12px', { lineHeight: '16px',  fontWeight: '500' }],
        'body-lg':            ['18px', { lineHeight: '28px',  fontWeight: '400' }],
        'body-md':            ['16px', { lineHeight: '24px',  fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px',  fontWeight: '700' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
