<?php

namespace App;

require_once __DIR__ . '/OrderControllerInterface.php';
// Asumsikan require autoload atau file manual sudah diurus oleh root index.php

class OrderController implements OrderControllerInterface {

    private OrderServiceInterface $orderService;
    private \App\ProductService $productService;
    private \App\RincianHppService $rincianHppService;

    public function __construct(
        OrderServiceInterface $orderService,
        \App\ProductService $productService,
        \App\RincianHppService $rincianHppService
    ) {
        $this->orderService       = $orderService;
        $this->productService     = $productService;
        $this->rincianHppService  = $rincianHppService;
    }

    private function buildCatalog(): array {
        $products = $this->productService->findAll();
        $hppList  = $this->rincianHppService->findAll();

        $hppByProductId = [];
        foreach ($hppList as $hpp) {
            if (!$hpp->getIsDeleted()) {
                $hppByProductId[$hpp->getProductId()] = $hpp;
            }
        }

        $catalog = [];
        foreach ($products as $p) {
            if ($p->getIsDeleted()) continue;
            $hpp = $hppByProductId[$p->getId()] ?? null;
            $catalog[] = [
                'id'    => $p->getId(),
                'name'  => $p->getName(),
                'price' => (float)$p->getPrice(),
                'modal' => $hpp ? (float)$hpp->getHppPerPcs() : 0.0,
            ];
        }
        return $catalog;
    }

    public function index(): void {
        $perPage = 20;
        $currentPage = max(1, (int)($_GET['p'] ?? 1));
        $totalOrders = $this->orderService->countAll();
        $totalPages = (int)ceil($totalOrders / $perPage);
        $currentPage = min($currentPage, max(1, $totalPages));

        $orders = $this->orderService->findPaginated($currentPage, $perPage);

        ob_start();
        require __DIR__ . '/../Views/Order/index.php';
        $content = ob_get_clean();

        require __DIR__ . '/../Views/layout.php';
    }

    public function create(): void {
        $catalogProducts = $this->buildCatalog();
        ob_start();
        require __DIR__ . '/../Views/Order/create.php';
        $content = ob_get_clean();
        require __DIR__ . '/../Views/layout.php';
    }

    public function store(array $data): void {
        if (!csrf_verify($data)) {
            header("Location: ?page=orders&action=create");
            exit;
        }
        $listItemOrder = $data['list_item_order'] ?? '[]';
        $subTotal = $data['subTotal'] ?? '0';

        // Logika simpan produk jastip baru secara otomatis
        try {
            $items = json_decode($listItemOrder, true);
            if (is_array($items)) {
                $conn = \App\Database::getConnection();
                foreach ($items as $item) {
                    $name = $item['name'] ?? '';
                    $price = $item['price'] ?? 0;
                    if (!empty($name)) {
                        // Insert jika belum ada, atau biarkan jika sudah ada (karena field name UNIQUE di DB)
                        $stmt = $conn->prepare("INSERT IGNORE INTO jastip_products (name, estimated_price) VALUES (?, ?)");
                        $stmt->execute([$name, $price]);
                        
                        // Opsional: Jika sudah ada, update request_count
                        if ($stmt->rowCount() == 0) {
                            $stmtUpdate = $conn->prepare("UPDATE jastip_products SET request_count = request_count + 1 WHERE name = ?");
                            $stmtUpdate->execute([$name]);
                        }
                    }
                }
            }
        } catch (\Exception $e) {
            // Lanjutkan meski ada error (misal tabel belum ada), karena ini fitur sampingan
            error_log("Gagal menyimpan jastip_product: " . $e->getMessage());
        }

        $order = new Order(
            0, 
            "", // OrderNumber will be generated by Service
            $listItemOrder,
            $subTotal,
            'Pending',
            json_encode([['status' => 'Pending', 'datetime' => (new \DateTime())->format('Y-m-d H:i:s')]]),
            $data['namaPemesan'] ?? '',
            $data['alamatPemesan'] ?? '',
            $data['whatsappPemesan'] ?? '',
            $data['instagramUserNamePemesan'] ?? '',
            new \DateTime(),
            new \DateTime()
        );

        $this->orderService->saveOrder($order);
        
        header("Location: index.php?page=orders");
        return;
    }

    public function show(string $orderNumber): void {
        $order = $this->orderService->findByOrderNumber($orderNumber);

        if(!$order) {
            http_response_code(404);
            echo "Order tidak ditemukan.";
            return;
        }

        ob_start();
        require __DIR__ . '/../Views/Order/show.php';
        $content = ob_get_clean();

        require __DIR__ . '/../Views/layout.php';
    }

    public function print(string $orderNumber): void {
        $order = $this->orderService->findByOrderNumber($orderNumber);

        if(!$order) {
            http_response_code(404);
            echo "Order tidak ditemukan.";
            return;
        }

        require __DIR__ . '/../Views/Order/print.php';
    }

    public function edit(string $orderNumber): void {
        $this->show($orderNumber);
    }

    public function editDetail(string $orderNumber): void {
        $order = $this->orderService->findByOrderNumber($orderNumber);
        if (!$order) {
            $_SESSION['error_message'] = "Order tidak ditemukan.";
            header("Location: ?page=orders");
            exit;
        }
        $catalogProducts = $this->buildCatalog();
        ob_start();
        require __DIR__ . '/../Views/Order/edit.php';
        $content = ob_get_clean();
        require __DIR__ . '/../Views/layout.php';
    }

    public function updateDetail(string $orderNumber, array $data): void {
        if (!csrf_verify($data)) {
            $_SESSION['error_message'] = "Permintaan tidak valid.";
            header("Location: ?page=orders&action=editDetail&id=" . urlencode($orderNumber));
            exit;
        }
        $order = $this->orderService->findByOrderNumber($orderNumber);
        if (!$order) {
            $_SESSION['error_message'] = "Order tidak ditemukan.";
            header("Location: ?page=orders");
            exit;
        }

        $namaPemesan = trim($data['namaPemesan'] ?? '');
        if ($namaPemesan !== '') $order->setNamaPemesan($namaPemesan);

        $whatsapp = trim($data['whatsappPemesan'] ?? '');
        if ($whatsapp !== '') $order->setWhatsappPemesan($whatsapp);

        $order->setInstagramUserNamePemesan(trim($data['instagramUserNamePemesan'] ?? ''));
        $order->setAlamatPemesan(trim($data['alamatPemesan'] ?? ''));

        $listItemOrder = $data['list_item_order'] ?? '[]';
        $items = json_decode($listItemOrder, true);
        if (!is_array($items) || empty($items)) {
            $_SESSION['error_message'] = "Minimal satu item harus diisi.";
            header("Location: ?page=orders&action=editDetail&id=" . urlencode($orderNumber));
            exit;
        }

        $order->setListItemOrder($listItemOrder);
        $order->setSubTotal($data['subTotal'] ?? '0');
        $order->setUpdatedAt(new \DateTime());

        $this->orderService->updateOrder($order);
        $_SESSION['success_message'] = "Detail order berhasil diupdate.";
        header("Location: ?page=orders&action=show&id=" . urlencode($orderNumber));
        exit;
    }

    public function update(string $orderNumber, array $data): void {
        if (!csrf_verify($data)) {
            header("Location: ?page=orders&action=show&id=" . urlencode($orderNumber));
            exit;
        }
        $order = $this->orderService->findByOrderNumber($orderNumber);

        if(!$order) {
            http_response_code(404);
            echo "Order tidak ditemukan.";
            return;
        }

        if(isset($data['orderStatus']) && trim($data['orderStatus']) !== '') {
            $newStatus = trim($data['orderStatus']);
            $newColor = $data['statusColor'] ?? 'blue';
            $newDetail = isset($data['statusDetail']) ? trim($data['statusDetail']) : '';
            
            if ($order->getOrderStatus() !== $newStatus || true) { // allow forcing color update even if text is same
                $order->setOrderStatus($newStatus);
                
                $historyStr = $order->getStatusHistory();
                $history = $historyStr ? json_decode($historyStr, true) : [];
                if (!is_array($history)) $history = [];
                
                // Jika status sama dengan yang terakhir, kita update warnanya dan detailnya saja
                $lastEntry = !empty($history) ? end($history) : null;
                if ($lastEntry && $lastEntry['status'] === $newStatus) {
                    $history[count($history)-1]['color'] = $newColor;
                    if ($newDetail !== '') {
                        $history[count($history)-1]['detail'] = $newDetail;
                    }
                } else {
                    $entry = [
                        'status' => $newStatus,
                        'datetime' => (new \DateTime())->format('Y-m-d H:i:s'),
                        'color' => $newColor
                    ];
                    if ($newDetail !== '') {
                        $entry['detail'] = $newDetail;
                    }
                    $history[] = $entry;
                }
                
                $order->setStatusHistory(json_encode($history));
            }
        }
        
        $order->setUpdatedAt(new \DateTime());
        
        $this->orderService->updateOrder($order);
        
        header("Location: index.php?page=orders&action=show&id=" . $orderNumber);
        return;
    }
}
